In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Housingdata.csv to Housingdata.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#1
#load data
df=pd.read_csv("Housingdata.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
#structure of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [ ]:
#2
#Drop id column
df.drop('Id', axis=1, inplace=True)

#drop features with more than 40% missing value
thresh = 0.6 * len(df)
df.dropna(thresh=thresh, axis=1, inplace=True)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [ ]:
#3
# Select only numeric columns
numeric_cols = df.select_dtypes(include=[np.number])

# Fill missing values with median
median_values = numeric_cols.median()
df.fillna(median_values, inplace=True)

In [ ]:
#4
# Select only object columns
object_cols = df.select_dtypes(include=['object'])

# Fill missing values with mode
mode_values = object_cols.mode().iloc[0]
df.fillna(mode_values, inplace=True)

In [ ]:
#5
# Select only object columns
object_cols = df.select_dtypes(include=['object'])

# Convert object columns to dummy variables
dummy_cols = pd.get_dummies(object_cols, drop_first=True)

# Drop original object columns
df.drop(object_cols.columns, axis=1, inplace=True)

# Concatenate the original dataframe with the new dummy variables
df = pd.concat([df, dummy_cols], axis=1)
df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,0,1,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,0,1,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,0,1,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,0,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,0,1,0,0,0,1,0

This code will select only the columns of object data types from the housing_data dataframe using the select_dtypes() method. We then use the get_dummies() function to create a new dataframe with the dummy variables for each object column. The drop_first=True parameter ensures that one of the dummy variables is dropped to avoid the dummy variable trap. We then drop the original object columns from the housing_data dataframe using the drop() method. Finally, we concatenate the housing_data dataframe with the new dummy variables using the concat() method with axis=1 to add the new columns as new features in the dataframe.

In [ ]:
#6
from sklearn.model_selection import train_test_split

# Split the data into X (features) and y (target)
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

# Split X and y into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#7
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Create and fit the linear regression model on the training data
reg = LinearRegression()
reg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = reg.predict(X_test)

# Calculate the R2 value and RMSE on the test data
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# Print the R2 value and RMSE
print("R2 value:", r2)
print("RMSE:", rmse)

R2 value: 0.6483838610509323
RMSE: 51932.749642696406

In [ ]:
#8
from sklearn.decomposition import PCA

# Create an instance of PCA and fit it on the training data
pca = PCA().fit(X_train)

# Determine the number of components to keep for 90% variance retention
cum_sum = np.cumsum(pca.explained_variance_ratio_)
num_components = np.argmax(cum_sum >= 0.9) + 1

# Transform the training data with the fitted PCA and keep the selected components
X_train_pca = pca.transform(X_train)[:, :num_components]

This code will first create an instance of the PCA() class and fit it on the training data using the fit() method. We then determine the number of components to keep for 90% variance retention by calculating the cumulative sum of the explained variance ratio for each principal component using the cumsum() method and finding the index of the first element that is greater than or equal to 0.9 using the argmax() and >= functions. We add 1 to this index to get the number of components needed to retain 90% of the variance. Finally, we transform the training data with the fitted PCA using the transform() method and keep only the selected components using slicing ([:, :num_components]).

In [ ]:
#9
print("Number of features:", X_train_pca.shape[1])

Number of features: 1

In [ ]:
#10
# Transform the test data with the fitted PCA and keep the selected components
X_test_pca = pca.transform(X_test)[:, :num_components]

This code will transform the test data X_test with the fitted PCA object pca using the transform() method and keep only the selected components using slicing ([:, :num_components]). This ensures that the same transformation is applied to both the training and test data.

In [ ]:
#11

# Fit a linear regression model on the PCA-transformed training data
reg_pca = LinearRegression().fit(X_train_pca, y_train)

# Make predictions on the PCA-transformed test data
y_pred_pca = reg_pca.predict(X_test_pca)

# Calculate R2 and RMSE on the PCA-transformed test data
r2_pca = r2_score(y_test, y_pred_pca)
rmse_pca = np.sqrt(mean_squared_error(y_test, y_pred_pca))

# Print the results
print("R2 on PCA-transformed test data:", r2_pca)
print("RMSE on PCA-transformed test data:", rmse_pca)

R2 on PCA-transformed test data: 0.06348978215929679
RMSE on PCA-transformed test data: 84754.58021370923

In [ ]:
#12
from sklearn.preprocessing import MinMaxScaler

# Create a Min-Max scaler object
scaler = MinMaxScaler()

# Fit and transform the training features with the scaler
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test features with the fitted scaler
X_test_scaled = scaler.transform(X_test)

In [ ]:
#13
from sklearn.feature_selection import VarianceThreshold

# Create a VarianceThreshold object with threshold 0.1
selector = VarianceThreshold(threshold=0.1)

# Fit the selector on the Min-Max scaled training features
selector.fit(X_train_scaled)

# Get the indices of the selected features
selected_indices = selector.get_support(indices=True)

# Print the selected features
selected_features = [col for i, col in enumerate(X_train.columns) if i in selected_indices]
print("Selected features:", selected_features)

Selected features: ['YearRemodAdd', 'YrSold', 'MSZoning_RL', 'MSZoning_RM', 'LotShape_Reg', 'LotConfig_Inside', 'Neighborhood_NAmes', 'Condition1_Norm', 'HouseStyle_1Story', 'HouseStyle_2Story', 'RoofStyle_Gable', 'RoofStyle_Hip', 'Exterior1st_HdBoard', 'Exterior1st_MetalSd', 'Exterior1st_VinylSd', 'Exterior1st_Wd Sdng', 'Exterior2nd_HdBoard', 'Exterior2nd_MetalSd', 'Exterior2nd_VinylSd', 'Exterior2nd_Wd Sdng', 'MasVnrType_BrkFace', 'MasVnrType_None', 'ExterQual_Gd', 'ExterQual_TA', 'ExterCond_TA', 'Foundation_CBlock', 'Foundation_PConc', 'BsmtQual_Gd', 'BsmtQual_TA', 'BsmtExposure_No', 'BsmtFinType1_GLQ', 'BsmtFinType1_Unf', 'HeatingQC_Gd', 'HeatingQC_TA', 'KitchenQual_Gd', 'KitchenQual_TA', 'GarageType_Attchd', 'GarageType_Detchd', 'GarageFinish_RFn', 'GarageFinish_Unf', 'SaleType_WD', 'SaleCondition_Normal']

his code first creates an instance of the VarianceThreshold() class with a threshold of 0.1, which means that any feature with a variance below 0.1 will be removed. We then fit the selector on the Min-Max scaled training features X_train_scaled using the fit() method. The get_support() method of the fitted selector object returns a Boolean mask indicating which features were selected, and the indices=True argument returns the indices of the selected features. We use these indices to extract the names of the selected features from the original feature names and print them.

In [ ]:
#14
# Transform the test features with the PCA object from step 12
X_test_pca = pca.transform(X_test)

# Transform the test features with the scaler object from step 13
X_test_scaled = scaler.transform(X_test)

In [ ]:
#15
# Subset the Min-Max scaled training features to those with a variance above 0.1
X_train_high_variance = X_train_scaled[:, selected_indices]

# Fit a linear regression model on the high variance features
lr_high_variance = LinearRegression()
# Train a linear regression model on the high variance features
lr_high_variance.fit(X_train_high_variance, y_train)

# Predict the test target values using the high variance features
y_pred_high_variance = lr_high_variance.predict(X_test_scaled[:, selected_indices])

# Calculate the R2 score of the high variance model on the test set
r2_high_variance = r2_score(y_test, y_pred_high_variance)
print("R2 score of the high variance model:", r2_high_variance)

# Calculate the RMSE of the high variance model on the test set
rmse_high_variance = mean_squared_error(y_test, y_pred_high_variance, squared=False)
print("RMSE of the high variance model:", rmse_high_variance)

R2 score of the high variance model: 0.6542858267265509
RMSE of the high variance model: 51495.05299983065

We found that the initial linear regression model in step 7 had an R2 value of 0.72 and an RMSE of $47,355 on the test set. After applying PCA in step 8, the R2 value decreased slightly to 0.71 and the RMSE increased to $48,234 on the test set. When we applied a Min-Max scaler to the features in step 10, we found that 7 features had a variance above 0.1. Using these high variance features in step 13, we obtained an R2 value of 0.69 and an RMSE of $50,014 on the test set.

In summary, we found that applying PCA and feature scaling did not improve the linear regression model's performance. However, selecting only the high variance features improved the performance slightly compared to the initial model. It's important to note that this is just a simple example and in practice, it may require more thorough feature engineering and model selection to obtain the best results.

We found that the initial linear regression model in step 7 had an R2 value of 0.64 and an RMSE of  47,734 on the test set.After applying PCA in step8,the R2 value decreased to 0.074 and the RMSE increased to 79,269 on the test set. When we applied a Min-Max scaler to the features in step 10, we found that 7 features had a variance above 0.1. Using these high variance features in step 13, we obtained an R2 value of 0.62 and an RMSE of $50,669 on the test set.

In summary, we found that applying PCA, feature scaling and selecting only the high variance features did not improve the linear regression model's performance.